name: PR Update

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
      - gh-actions-test-branch
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changes
    runs-on: buildjet-2vcpu-ubuntu-2204
    permissions:
      pull-requests: read
    outputs:
      has-files-requiring-all-checks: ${{ steps.filter.outputs.has-files-requiring-all-checks }}
      commit-sha: ${{ steps.get_sha.outputs.commit-sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            has-files-requiring-all-checks:
              - "!(**.md|.github/CODEOWNERS)"
      - name: Get Latest Commit SHA
        id: get_sha
        run: |
          echo "commit-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  deps:
    name: Install dependencies
    needs: [changes]
    uses: ./.github/workflows/yarn-install.yml

  type-check:
    name: Type check
    needs: [changes, deps]
    uses: ./.github/workflows/check-types.yml
    secrets: inherit

  lint:
    name: Linters
    needs: [changes, deps]
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  unit-test:
    name: Tests
    needs: [changes, deps]
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  build-api-v1:
    name: Production builds
    needs: [changes, deps]
    uses: ./.github/workflows/api-v1-production-build.yml
    secrets: inherit

  build-api-v2:
    name: Production builds
    needs: [changes, deps]
    uses: ./.github/workflows/api-v2-production-build.yml
    secrets: inherit

  build-atoms:
    name: Production builds
    needs: [changes, deps]
    uses: ./.github/workflows/atoms-production-build.yml
    secrets: inherit

  build:
    name: Production builds
    needs: [changes, deps]
    uses: ./.github/workflows/production-build-without-database.yml
    secrets: inherit

  integration-test:
    name: Tests
    needs: [changes, build, build-api-v1, build-api-v2]
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit

  e2e:
    name: Tests
    needs: [changes, build, build-api-v1, build-api-v2]
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  e2e-api-v2:
    name: Tests
    needs: [changes, build, build-api-v1, build-api-v2]
    uses: ./.github/workflows/e2e-api-v2.yml
    secrets: inherit

  e2e-app-store:
    name: Tests
    needs: [changes, build, build-api-v1, build-api-v2]
    uses: ./.github/workflows/e2e-app-store.yml
    secrets: inherit

  e2e-embed:
    name: Tests
    needs: [changes, build, build-api-v1, build-api-v2]
    uses: ./.github/workflows/e2e-embed.yml
    secrets: inherit

  e2e-embed-react:
    name: Tests
    needs: [changes, build, build-api-v1, build-api-v2]
    uses: ./.github/workflows/e2e-embed-react.yml
    secrets: inherit

  analyze:
    name: Analyze Build
    needs: [build]
    uses: ./.github/workflows/nextjs-bundle-analysis.yml
    secrets: inherit

  merge-reports:
    name: Merge reports
    needs: [changes, e2e, e2e-embed, e2e-embed-react, e2e-app-store]
    uses: ./.github/workflows/merge-reports.yml
    secrets: inherit

  publish-report:
    name: Publish HTML report
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: [changes, merge-reports]
    uses: ./.github/workflows/publish-report.yml
    secrets: inherit

  required:
    needs:
      [
        changes,
        lint,
        type-check,
        unit-test,
        integration-test,
        build,
        build-api-v1,
        build-api-v2,
        e2e,
        e2e-api-v2,
        e2e-embed,
        e2e-embed-react,
        e2e-app-store,
      ]
    if: always()
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: fail if any job failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
        